/**
 * @module prompts/gold-standards-core
 *
 * Core gold standard responses for auto-tuning. Contains hardcoded ideal
 * (tier 1), good (tier 2), and acceptable (tier 3) reference responses
 * generated by a gold standard model (Claude Opus 4.6). Covers `core.*`
 * prompts: insight synthesis, breakthrough validation, novelty gate, question
 * generation/answering, research cycle, and autorating.
 */

import { loadGoldStandard } from './loader.js';

const CAT = 'core';

/**
 * A single gold standard reference response for auto-tune scoring.
 *
 * @property promptId - The prompt ID this gold standard applies to (e.g. `'core.insight_synthesis'`).
 * @property tier - Quality tier: 1 = ideal (best possible), 2 = good (solid), 3 = acceptable (minimum passing).
 * @property content - The reference response content that models are scored against.
 */
export interface DefaultGoldStandard {
    promptId: string;
    tier: 1 | 2 | 3;
    content: string;
}

/**
 * Core gold standard responses for `core.*` prompts. Each entry pairs a
 * prompt ID with a quality tier and reference content used as the scoring
 * baseline when no DB-generated gold standards exist.
 */
export const CORE_GOLD_STANDARDS: DefaultGoldStandard[] = [
    { promptId: 'core.insight_synthesis', tier: 1, content: loadGoldStandard(CAT, 'core.insight_synthesis', 1) },
    { promptId: 'core.insight_synthesis', tier: 2, content: loadGoldStandard(CAT, 'core.insight_synthesis', 2) },
    { promptId: 'core.insight_synthesis', tier: 3, content: loadGoldStandard(CAT, 'core.insight_synthesis', 3) },
    { promptId: 'core.multi_insight_synthesis', tier: 1, content: loadGoldStandard(CAT, 'core.multi_insight_synthesis', 1) },
    { promptId: 'core.multi_insight_synthesis', tier: 2, content: loadGoldStandard(CAT, 'core.multi_insight_synthesis', 2) },
    { promptId: 'core.multi_insight_synthesis', tier: 3, content: loadGoldStandard(CAT, 'core.multi_insight_synthesis', 3) },
    { promptId: 'core.breakthrough_validation', tier: 1, content: loadGoldStandard(CAT, 'core.breakthrough_validation', 1) },
    { promptId: 'core.breakthrough_validation', tier: 2, content: loadGoldStandard(CAT, 'core.breakthrough_validation', 2) },
    { promptId: 'core.breakthrough_validation', tier: 3, content: loadGoldStandard(CAT, 'core.breakthrough_validation', 3) },
    { promptId: 'core.novelty_gate', tier: 1, content: loadGoldStandard(CAT, 'core.novelty_gate', 1) },
    { promptId: 'core.novelty_gate', tier: 2, content: loadGoldStandard(CAT, 'core.novelty_gate', 2) },
    { promptId: 'core.novelty_gate', tier: 3, content: loadGoldStandard(CAT, 'core.novelty_gate', 3) },
    { promptId: 'core.question_generation', tier: 1, content: loadGoldStandard(CAT, 'core.question_generation', 1) },
    { promptId: 'core.question_generation', tier: 2, content: loadGoldStandard(CAT, 'core.question_generation', 2) },
    { promptId: 'core.question_generation', tier: 3, content: loadGoldStandard(CAT, 'core.question_generation', 3) },
    { promptId: 'core.question_answer', tier: 1, content: loadGoldStandard(CAT, 'core.question_answer', 1) },
    { promptId: 'core.question_answer', tier: 2, content: loadGoldStandard(CAT, 'core.question_answer', 2) },
    { promptId: 'core.question_answer', tier: 3, content: loadGoldStandard(CAT, 'core.question_answer', 3) },
    { promptId: 'core.research_cycle', tier: 1, content: loadGoldStandard(CAT, 'core.research_cycle', 1) },
    { promptId: 'core.research_cycle', tier: 2, content: loadGoldStandard(CAT, 'core.research_cycle', 2) },
    { promptId: 'core.research_cycle', tier: 3, content: loadGoldStandard(CAT, 'core.research_cycle', 3) },
    { promptId: 'core.autorating', tier: 1, content: loadGoldStandard(CAT, 'core.autorating', 1) },
    { promptId: 'core.autorating', tier: 2, content: loadGoldStandard(CAT, 'core.autorating', 2) },
    { promptId: 'core.autorating', tier: 3, content: loadGoldStandard(CAT, 'core.autorating', 3) },
];
