/**
 * @module core/autotune/gold-standards
 *
 * Gold standard reference response management for auto-tune scoring.
 *
 * Gold standards are 3-tier reference responses (ideal, good, acceptable)
 * generated by the `tuning_judge` model for each operational prompt.
 * During auto-tune, model outputs are scored by embedding similarity
 * to these references, weighted by tier quality.
 */

import { RC } from '../../config/constants.js';
import { callSubsystemModel, getEmbedding } from '../../models.js';
import { getPrompt, DEFAULT_GOLD_STANDARDS } from '../../prompts.js';
import { systemQuery as query } from '../../db/index.js';
import { ensureAssignmentsLoaded, getAssignedModel } from '../../models/assignments.js';
import { cosineSimilarity, parseEmbedding, embeddingToBuffer } from '../scoring.js';
import type { QualityScore, SubsystemCategory, GoldStandard } from './types.js';
import { PROMPT_CATEGORY_MAP, getPromptIdsForCategory, loadTestVars } from './scoring.js';

/**
 * Compose a fully-interpolated prompt using the operational prompt + test variables.
 *
 * This is the CANONICAL prompt used for both gold standard generation and auto-tune
 * testing. Test variables are loaded from `autotune.data.*` prompts (editable via GUI).
 *
 * @param promptId - Operational prompt ID (e.g., 'core.insight_synthesis')
 * @returns Fully interpolated prompt string, or `null` if test vars are not configured
 */
export async function composeTestPrompt(promptId: string): Promise<string | null> {
    const testVars = await loadTestVars(promptId);
    if (!testVars) return null;
    return getPrompt(promptId, testVars);
}

/**
 * Generate 3-tier gold standard responses for a prompt using the tuning_judge model.
 *
 * Called automatically when a user saves or reverts a prompt. Skips locked tiers
 * (manually edited). Each tier uses a different judge meta-prompt to produce
 * ideal (tier 1), good (tier 2), and acceptable (tier 3) reference responses.
 *
 * @param promptId - Operational prompt ID to generate gold standards for
 * @returns Object with `generated` count and optional `error` message
 */
export async function generateGoldStandards(promptId: string): Promise<{ generated: number; error?: string }> {
    if (!PROMPT_CATEGORY_MAP[promptId]) {
        console.warn(`[tuning-judge] ${promptId}: not in PROMPT_CATEGORY_MAP — cannot generate gold standards`);
        return { generated: 0, error: `Prompt "${promptId}" is not configured for gold standard generation (missing from PROMPT_CATEGORY_MAP)` };
    }

    await ensureAssignmentsLoaded();
    const judge = getAssignedModel('tuning_judge');
    if (!judge) return { generated: 0, error: 'No model assigned to tuning_judge subsystem' };

    console.log(`[tuning-judge] Generating gold standards for ${promptId} using ${judge.name}...`);

    // Compose the prompt with test variables properly filled in
    // This is the same prompt that auto-tune will use when testing
    const composedPrompt = await composeTestPrompt(promptId);
    if (!composedPrompt) {
        return { generated: 0, error: `Failed to compose test prompt for ${promptId} (missing TEST_VAR_CONFIGS entry or data prompts)` };
    }

    const tiers = [1, 2, 3] as const;
    let generated = 0;

    // Check which tiers are locked (manually edited) — skip those
    let lockedTiers: Set<number> = new Set();
    try {
        const lockedRows = await query(
            `SELECT tier FROM prompt_gold_standards WHERE prompt_id = $1 AND locked = 1`,
            [promptId],
        );
        lockedTiers = new Set(lockedRows.map((r: any) => r.tier));
    } catch { /* locked column may not exist yet */ }

    for (const tier of tiers) {
        if (lockedTiers.has(tier)) {
            console.log(`[tuning-judge] Skipping locked tier ${tier} for ${promptId}`);
            continue;
        }

        const judgeMetaPrompt = await getPrompt(`autotune.judge_tier${tier}`, {
            prompt: composedPrompt,
            input: '',  // All data is already in the composed prompt
        });

        try {
            const response = await callSubsystemModel('tuning_judge', judgeMetaPrompt);

            if (!response || response.trim().length === 0) {
                console.warn(`[tuning-judge] Empty response for ${promptId} tier ${tier}`);
                continue;
            }

            // Generate embedding for similarity scoring
            let embeddingBuf: Buffer | null = null;
            try {
                const emb = await getEmbedding(response);
                if (emb) {
                    embeddingBuf = embeddingToBuffer(emb);
                }
            } catch (embErr: any) {
                console.warn(`[tuning-judge] Embedding failed for ${promptId} tier ${tier}: ${embErr.message}`);
            }

            // Upsert into DB
            await query(
                `INSERT INTO prompt_gold_standards (id, prompt_id, tier, content, test_input, embedding, model_used, generated_at)
                 VALUES (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',abs(random())%4+1,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6))),
                         $1, $2, $3, $4, $5, $6, datetime('now'))
                 ON CONFLICT(prompt_id, tier) DO UPDATE SET
                     content = excluded.content,
                     test_input = excluded.test_input,
                     embedding = excluded.embedding,
                     model_used = excluded.model_used,
                     generated_at = excluded.generated_at`,
                [promptId, tier, response.trim(), composedPrompt, embeddingBuf, judge.name],
            );

            generated++;
            console.log(`[tuning-judge] Generated tier ${tier} gold standard for ${promptId} (${response.trim().length} chars)`);
        } catch (err: any) {
            console.error(`[tuning-judge] Failed tier ${tier} for ${promptId}: ${err.message}`);
        }
    }

    return { generated };
}

/**
 * Get all gold standard reference responses for a prompt, ordered by tier.
 *
 * @param promptId - Operational prompt ID
 * @returns Array of gold standard records (tier 1, 2, 3)
 */
export async function getGoldStandards(promptId: string): Promise<GoldStandard[]> {
    const rows = await query(
        `SELECT id, prompt_id, tier, content, test_input, embedding, model_used, COALESCE(locked, 0) as locked, generated_at
         FROM prompt_gold_standards
         WHERE prompt_id = $1
         ORDER BY tier ASC`,
        [promptId],
    );
    return rows as GoldStandard[];
}

/**
 * Delete all gold standard reference responses for a prompt.
 *
 * @param promptId - Operational prompt ID whose gold standards to delete
 */
export async function deleteGoldStandards(promptId: string): Promise<void> {
    await query(
        `DELETE FROM prompt_gold_standards WHERE prompt_id = $1`,
        [promptId],
    );
}

/**
 * Update a gold standard's content and/or locked state.
 *
 * When content is edited, the embedding is regenerated and the record is
 * auto-locked (locked records are skipped during regeneration).
 *
 * @param id - Gold standard record ID
 * @param updates - Fields to update: `content` (triggers re-embed + auto-lock)
 *                  and/or `locked` (toggle lock without editing content)
 */
export async function updateGoldStandard(
    id: string,
    updates: { content?: string; locked?: boolean },
): Promise<void> {
    if (updates.content !== undefined) {
        // Content edit — regenerate embedding and auto-lock
        let embeddingBuf: Buffer | null = null;
        try {
            const emb = await getEmbedding(updates.content);
            if (emb) embeddingBuf = embeddingToBuffer(emb);
        } catch (err: any) {
            console.warn(`[tuning-judge] Embedding regeneration failed for ${id}: ${err.message}`);
        }

        await query(
            `UPDATE prompt_gold_standards
             SET content = $1, embedding = $2, locked = 1, model_used = 'manual', generated_at = datetime('now')
             WHERE id = $3`,
            [updates.content, embeddingBuf, id],
        );
    }

    if (updates.locked !== undefined && updates.content === undefined) {
        // Just toggling the lock without editing content
        await query(
            `UPDATE prompt_gold_standards SET locked = $1 WHERE id = $2`,
            [updates.locked ? 1 : 0, id],
        );
    }
}

/**
 * List all prompts that have gold standard reference responses.
 *
 * @returns Array of objects with prompt_id, count of tiers, and latest generated_at timestamp
 */
export async function listGoldStandardPrompts(): Promise<{ prompt_id: string; count: number; generated_at: string }[]> {
    const rows = await query(
        `SELECT prompt_id, COUNT(*) as count, MAX(generated_at) as generated_at
         FROM prompt_gold_standards
         GROUP BY prompt_id
         ORDER BY prompt_id`,
    );
    return rows as any[];
}

// =============================================================================
// GOLD STANDARD — SCORING
// =============================================================================

/**
 * Score a model's output against gold standard reference responses.
 *
 * Compares the output's embedding similarity to each tier's reference,
 * weighted by tier quality: tier 1 = 1.0, tier 2 = 0.85, tier 3 = 0.65.
 * Returns the highest weighted similarity as the overall score.
 *
 * Falls back to hardcoded default gold standards if none exist in the DB.
 *
 * @param output - Raw LLM output to score
 * @param category - Subsystem category (determines which prompts to check)
 * @param goldPromptId - Optional specific prompt ID to score against;
 *                       if omitted, falls back to the first prompt in the category that has any
 * @returns Quality score with gold standard dimensions, or `null` if no gold standards exist
 */
export async function scoreAgainstGoldStandards(output: string, category: SubsystemCategory, goldPromptId?: string): Promise<QualityScore | null> {
    let goldRows: any[] = [];

    if (goldPromptId) {
        goldRows = await query(
            `SELECT tier, content, embedding FROM prompt_gold_standards WHERE prompt_id = $1 ORDER BY tier`,
            [goldPromptId],
        );
    } else {
        // Fallback: find any prompt in this category that has gold standards
        const promptIds = getPromptIdsForCategory(category);
        for (const pid of promptIds) {
            goldRows = await query(
                `SELECT tier, content, embedding FROM prompt_gold_standards WHERE prompt_id = $1 ORDER BY tier`,
                [pid],
            );
            if (goldRows.length > 0) break;
        }
    }

    // Fallback to hardcoded defaults when no DB gold standards exist
    if (goldRows.length === 0) {
        const lookupIds = goldPromptId ? [goldPromptId] : getPromptIdsForCategory(category);
        const defaults = DEFAULT_GOLD_STANDARDS.filter(gs => lookupIds.includes(gs.promptId));
        if (defaults.length === 0) return null;

        const outputEmb = await getEmbedding(output);
        if (!outputEmb) return null;

        const tierWeights: Record<number, number> = { 1: RC.scoring.goldStandardTierWeights.tier1, 2: RC.scoring.goldStandardTierWeights.tier2, 3: RC.scoring.goldStandardTierWeights.tier3 };
        const dims: Record<string, number> = {};
        let bestScore = 0;

        for (const gs of defaults) {
            const tierEmb = await getEmbedding(gs.content);
            if (!tierEmb) continue;

            const sim = cosineSimilarity(outputEmb, tierEmb);
            const weighted = sim * (tierWeights[gs.tier] || RC.scoring.goldStandardFallbackWeight);
            dims[`goldTier${gs.tier}`] = sim;
            dims[`goldTier${gs.tier}Weighted`] = weighted;

            if (weighted > bestScore) bestScore = weighted;
        }

        dims.goldBestScore = bestScore;
        dims.goldSource = 0; // 0 = hardcoded defaults
        return { overall: bestScore, dimensions: dims, rawOutput: output };
    }

    // Generate embedding for the model's output
    const outputEmb = await getEmbedding(output);
    if (!outputEmb) return null;

    const tierWeights: Record<number, number> = { 1: RC.scoring.goldStandardTierWeights.tier1, 2: RC.scoring.goldStandardTierWeights.tier2, 3: RC.scoring.goldStandardTierWeights.tier3 };
    const dims: Record<string, number> = {};
    let bestScore = 0;

    for (const row of goldRows) {
        const tierEmb = parseEmbedding(row.embedding);
        if (!tierEmb) continue;

        const sim = cosineSimilarity(outputEmb, tierEmb);
        const weighted = sim * (tierWeights[row.tier] || RC.scoring.goldStandardFallbackWeight);
        dims[`goldTier${row.tier}`] = sim;
        dims[`goldTier${row.tier}Weighted`] = weighted;

        if (weighted > bestScore) bestScore = weighted;
    }

    dims.goldBestScore = bestScore;
    dims.goldSource = 1; // 1 = DB-generated

    return { overall: bestScore, dimensions: dims, rawOutput: output };
}
